#/*** @author Raquif Roshan * */
spring:
  application:
    name: CricketRestApiH2Data
  datasource:
    url: jdbc:h2:mem:testdb

    driver-class-name: org.h2.Driver
    username: user
    password: password 
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
   

    
    
server:
  port: 8092
  
  
  